"""init ind_fum

Revision ID: f28ee8378e36
Revises: 
Create Date: 2024-11-11 00:39:32.914410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28ee8378e36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=128), nullable=False),
    sa.Column('media_type', sa.Enum('PHOTO', 'DOCUMENT', 'VIDEO', 'VOICE', 'AUDIO', 'VIDEO_NOTE', name='mediatype'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'file_id')
    )
    op.create_table('reply',
    sa.Column('reply_in', sa.Integer(), nullable=False),
    sa.Column('reply_to', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reply_in'], ['message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reply_in', 'reply_to')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('message_file')
    # ### end Alembic commands ###
