"""fix 1

Revision ID: f2fb19a332f9
Revises: 
Create Date: 2024-11-11 02:52:06.644873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2fb19a332f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('ADMIN', 'SUPERUSER', 'USER', name='usertype'), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('nick_name', sa.String(length=128), nullable=True),
    sa.Column('datetime_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datetime_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pk')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('caption', sa.Text(length=4096), nullable=False),
    sa.Column('datetime_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datetime_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='message_pk')
    )
    op.create_table('user_notif',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'file_id')
    )
    op.create_table('message_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=128), nullable=False),
    sa.Column('media_type', sa.Enum('PHOTO', 'DOCUMENT', 'VIDEO', 'VOICE', 'AUDIO', 'VIDEO_NOTE', name='mediatype'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'file_id', name='message_file_pk')
    )
    op.create_table('reply',
    sa.Column('reply_in', sa.Integer(), nullable=False),
    sa.Column('reply_to', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reply_in'], ['message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reply_in', 'reply_to')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('message_file')
    op.drop_table('user_notif')
    op.drop_table('message')
    op.drop_table('user')
    # ### end Alembic commands ###
